import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "DANDY privacy policy — how we collect, use and protect your personal information when you shop with us.",
  alternates: { canonical: "/privacy" },
};

export default function Page() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-10 sm:py-16 md:px-8">
      <h1 className="font-serif text-4xl sm:text-5xl">Privacy Policy</h1>
      <p className="mt-2 text-xs text-ink-soft">Last updated: September 2026</p>

      <div className="mt-10 space-y-10 leading-relaxed text-sm sm:text-base">
        <section>
          <h2 className="font-serif text-xl sm:text-2xl">1. Who We Are</h2>
          <p className="mt-3">
            Dandy Bags is a sole proprietorship based in Karur, Tamil Nadu – 639002, India.
            We operate the DANDY website and sell bags and luggage online and through selected retail
            channels. For privacy and grievance matters, you may contact us at{" "}
            <a href="mailto:dandybagsofficial@gmail.com" className="text-ink underline underline-offset-4">dandybagsofficial@gmail.com</a>.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl sm:text-2xl">2. Information We Collect</h2>
          <p className="mt-3">
            We collect only the information reasonably needed to process orders, maintain accounts and
            communicate with you. This includes:
          </p>
          <ul className="mt-3 list-disc space-y-2 pl-5">
            <li>Name, email address and mobile number</li>
            <li>Delivery address and contact details</li>
            <li>Order history, items purchased and payment status</li>
            <li>Payment identifiers generated by Razorpay (such as Razorpay order ID and payment ID)</li>
            <li>Account credentials (stored in hashed form)</li>
            <li>Wishlist and cart items</li>
            <li>Reviews and ratings</li>
            <li>Coupon usage and Share &amp; Earn submissions</li>
            <li>Password reset and email verification tokens</li>
            <li>Customer support communications</li>
          </ul>
        </section>

        <section>
          <h2 className="font-serif text-xl sm:text-2xl">3. How We Collect Information</h2>
          <p className="mt-3">
            Information is collected when you create an account, place an order, join the Share &amp; Earn
            programme, write a review or contact us. We also receive certain data automatically from your
            browser or device where necessary for security and basic site operation.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl sm:text-2xl">4. Why We Use Information</h2>
          <p className="mt-3">
            We use your information for purposes including:
          </p>
          <ul className="mt-3 list-disc space-y-2 pl-5">
            <li>Processing and delivering orders</li>
            <li>Sending order confirmations and status updates</li>
            <li>Managing your account and authentication</li>
            <li>Processing payments and preventing fraud</li>
            <li>Responding to customer support requests</li>
            <li>Improving our products and services</li>
            <li>Complying with legal and accounting obligations</li>
          </ul>
        </section>

        <section>
          <h2 className="font-serif text-xl sm:text-2xl">5. Account and Authentication Data</h2>
          <p className="mt-3">
            Your account is protected by a password. Passwords are stored in hashed form and cannot be
            read by us. You are responsible for maintaining the confidentiality of your login details.
          </p>
          <p className="mt-3">
            We use session cookies to keep you logged in securely. These cookies are essential for
            account functionality and do not track your activity across other websites.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl sm:text-2xl">6. Orders and Delivery Data</h2>
          <p className="mt-3">
            When you place an order, we store the items purchased, quantities, prices, delivery address
            and order status. This information is used to fulfil, ship and support your order, and for
            accounting and legal records.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl sm:text-2xl">7. Payment Information</h2>
          <p className="mt-3">
            Payments are processed by Razorpay. DANDY does not store your full card number, UPI PIN or
            other sensitive banking credentials. We retain only the Razorpay order ID and payment ID
            needed to match payments to orders and provide customer support.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl sm:text-2xl">8. Customer Communications</h2>
          <p className="mt-3">
            We may send you transactional emails related to your account and orders, such as
            verification, password reset and order confirmation. We do not send promotional emails
            unless you have opted in.
          </p>
          <p className="mt-3">
            Support enquiries sent by email or WhatsApp are retained for reference and quality purposes.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl sm:text-2xl">9. Wishlist, Cart, Reviews, Coupons and Share &amp; Earn</h2>
          <p className="mt-3">
            Wishlist and cart data may be stored locally on your device and, when you are logged in,
            linked to your account. Reviews, coupon usage and Share &amp; Earn submissions are stored
            with your account information to operate these features.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl sm:text-2xl">10. Cookies and Similar Technologies</h2>
          <p className="mt-3">
            We use essential cookies and similar technologies necessary for the functioning of the
            website and your account. These include the authentication session cookie and, where
            applicable, local storage for your shopping cart.
          </p>
          <p className="mt-3">
            We do not currently use advertising or analytics cookies. If this changes, we will update
            this policy and obtain any required consent.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl sm:text-2xl">11. Third-Party Service Providers</h2>
          <p className="mt-3">
            We work with the following service providers who may process your information on our behalf:
          </p>
          <ul className="mt-3 list-disc space-y-2 pl-5">
            <li>
              <strong>Razorpay</strong> — payment processing; subject to Razorpay&apos;s privacy policy
            </li>
            <li>
              <strong>Resend</strong> — transactional email delivery; subject to Resend&apos;s privacy
              policy
            </li>
            <li>
              <strong>Supabase / PostgreSQL</strong> — database hosting; subject to Supabase&apos;s
              terms
            </li>
            <li>
              <strong>Vercel</strong> — website hosting and delivery; subject to Vercel&apos;s privacy
              policy
            </li>
            <li>
              <strong>Google Fonts</strong> — typography; subject to Google&apos;s privacy policy
            </li>
          </ul>
          <p className="mt-3">
            These providers are contractually required to protect your data and use it only for the
            purposes we specify. Their own privacy policies govern their handling of your information.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl sm:text-2xl">12. Data Security</h2>
          <p className="mt-3">
            We implement reasonable technical and organisational measures to protect your personal data,
            including encrypted session cookies, hashed passwords, server-side access controls and
            secure database connections.
          </p>
          <p className="mt-3">
            No method of transmission or storage is 100% secure. While we strive to protect your data,
            we cannot guarantee absolute security.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl sm:text-2xl">13. Data Retention</h2>
          <p className="mt-3">
            We retain order, account and transaction records for as long as needed for business,
            accounting, legal and tax purposes. Some data may need to be kept beyond the lifetime of
            your account to comply with statutory obligations or resolve disputes.
          </p>
          <p className="mt-3">
            If you close your account or request deletion, we will delete or anonymise personal data
            where no legal or business retention requirement exists.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl sm:text-2xl">14. Customer Privacy Requests</h2>
          <p className="mt-3">
            You may request access to or correction of your personal data by contacting us. We will
            respond within a reasonable timeframe, subject to verification of your identity.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl sm:text-2xl">15. Data Deletion Requests</h2>
          <p className="mt-3">
            If you wish to request deletion of your personal data, please write to{" "}
            <a href="mailto:dandybagsofficial@gmail.com" className="text-ink underline underline-offset-4">dandybagsofficial@gmail.com</a>.
            We will assess the request and delete or anonymise data where legally and operationally
            possible. Certain records may need to be retained for compliance with tax, accounting,
            fraud-prevention or legal obligations.
          </p>
          <p className="mt-3">
            Please note that a self-service account deletion feature is not currently available on this
            website. Deletion requests must be made by email.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl sm:text-2xl">16. Children&apos;s Privacy</h2>
          <p className="mt-3">
            This website is intended for use by individuals who have the legal capacity to enter into
            transactions. Where applicable, a parent or guardian should supervise or authorise purchases
            by minors. We do not knowingly collect personal information from children without appropriate
            consent.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl sm:text-2xl">17. Changes to Privacy Policy</h2>
          <p className="mt-3">
            We may update this policy from time to time. The updated version will be posted on this
            page with a revised date. Material changes will be highlighted where feasible.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl sm:text-2xl">18. Contact / Grievance</h2>
          <p className="mt-3">
            For privacy questions, data requests or grievances, contact:
          </p>
          <p className="mt-2">
            <strong>Grievance Officer:</strong> Muhammad Salih A M<br />
            <strong>Designation:</strong> Grievance Officer, Dandy Bags<br />
            <strong>Email:</strong>{" "}
            <a href="mailto:dandybagsofficial@gmail.com" className="text-ink underline underline-offset-4">dandybagsofficial@gmail.com</a><br />
            <strong>Phone:</strong>{" "}
            <a href="tel:+919047633332" className="text-ink underline underline-offset-4">+91 90476 33332</a>
          </p>
        </section>
      </div>
    </div>
  );
}
